<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Dashboard</name>
   <tag></tag>
   <elementGuidId>50f6cbce-a4e9-454c-a3a5-260ee1791f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/main/div/div/div[2]/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss48 > h2.MuiTypography-root.MuiTypography-h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>7f4d6159-580e-437c-903d-a3630d1d8033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h2</value>
      <webElementGuid>3c71e3de-c638-4f29-9089-46fc9fc34be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard</value>
      <webElementGuid>5655b73b-56f6-42be-9dd5-57f98ddec22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;sc-cLpAjG bOrrQs&quot;]/main[@class=&quot;sc-kmQMED fjprRt&quot;]/div[@class=&quot;sc-cvZCdy dRvMaC&quot;]/div[@class=&quot;MuiBox-root jss47&quot;]/div[@class=&quot;MuiBox-root jss48&quot;]/h2[@class=&quot;MuiTypography-root MuiTypography-h2&quot;]</value>
      <webElementGuid>37f0bf52-8372-49a3-9768-0b14b8efddd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div/div/div[2]/h2</value>
      <webElementGuid>c43d9b6c-cc09-4d19-9bb4-716c29ed85c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::h2[1]</value>
      <webElementGuid>7a5f3280-5da5-4a63-ad9b-1abc56140b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/following::h2[1]</value>
      <webElementGuid>f1528c8e-d02e-4839-9edc-4542dfa4398e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$4,28...'])[1]/preceding::h2[1]</value>
      <webElementGuid>89340d0a-cd07-4f5e-aaa4-b47faaad42fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/h2</value>
      <webElementGuid>ca002003-1226-46bd-82a3-779a535ae00a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Dashboard' or . = 'Dashboard')]</value>
      <webElementGuid>af36e9e8-ed4f-4387-bddf-6d53a8a96f91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
